"""Add api_call_logs table

Revision ID: cd2de2f02b3b
Revises: 004
Create Date: 2026-05-27 14:48:41.851697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd2de2f02b3b'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_call_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('request_body', sa.JSON(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_call_logs_path'), 'api_call_logs', ['path'], unique=False)
    op.create_index('ix_api_call_logs_path_timestamp', 'api_call_logs', ['path', 'timestamp'], unique=False)
    op.create_index(op.f('ix_api_call_logs_response_status'), 'api_call_logs', ['response_status'], unique=False)
    op.create_index('ix_api_call_logs_response_status_timestamp', 'api_call_logs', ['response_status', 'timestamp'], unique=False)
    op.create_index(op.f('ix_api_call_logs_timestamp'), 'api_call_logs', ['timestamp'], unique=False)
    op.create_table('comm_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comm_logs_device_id'), 'comm_logs', ['device_id'], unique=False)
    op.create_index('ix_comm_logs_device_timestamp', 'comm_logs', ['device_id', 'timestamp'], unique=False)
    op.create_index('ix_comm_logs_event_type', 'comm_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_comm_logs_timestamp'), 'comm_logs', ['timestamp'], unique=False)
    op.create_table('memory_convers_episodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('summary', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('learned_facts', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_convers_episodes_entity_id'), 'memory_convers_episodes', ['entity_id'], unique=False)
    op.create_table('memory_convers_preferences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('preference_type', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_convers_preferences_entity_id'), 'memory_convers_preferences', ['entity_id'], unique=False)
    op.create_table('memory_convers_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('summary', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_convers_sessions_entity_id'), 'memory_convers_sessions', ['entity_id'], unique=False)
    op.create_table('memory_infra_devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_infra_devices_entity_id'), 'memory_infra_devices', ['entity_id'], unique=False)
    op.drop_table('import_postgres_export')
    op.drop_table('skill_definitions')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_user_email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_user_email', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_table('skill_definitions',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('output_schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_builtin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name=op.f('skill_definitions_pkey'))
    )
    op.create_table('import_postgres_export',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('businessgroupid', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('businessgroupname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('businessgroupidpath', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('businessgroupnamepath', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fault', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_memory_infra_devices_entity_id'), table_name='memory_infra_devices')
    op.drop_table('memory_infra_devices')
    op.drop_index(op.f('ix_memory_convers_sessions_entity_id'), table_name='memory_convers_sessions')
    op.drop_table('memory_convers_sessions')
    op.drop_index(op.f('ix_memory_convers_preferences_entity_id'), table_name='memory_convers_preferences')
    op.drop_table('memory_convers_preferences')
    op.drop_index(op.f('ix_memory_convers_episodes_entity_id'), table_name='memory_convers_episodes')
    op.drop_table('memory_convers_episodes')
    op.drop_index(op.f('ix_comm_logs_timestamp'), table_name='comm_logs')
    op.drop_index('ix_comm_logs_event_type', table_name='comm_logs')
    op.drop_index('ix_comm_logs_device_timestamp', table_name='comm_logs')
    op.drop_index(op.f('ix_comm_logs_device_id'), table_name='comm_logs')
    op.drop_table('comm_logs')
    op.drop_index(op.f('ix_api_call_logs_timestamp'), table_name='api_call_logs')
    op.drop_index('ix_api_call_logs_response_status_timestamp', table_name='api_call_logs')
    op.drop_index(op.f('ix_api_call_logs_response_status'), table_name='api_call_logs')
    op.drop_index('ix_api_call_logs_path_timestamp', table_name='api_call_logs')
    op.drop_index(op.f('ix_api_call_logs_path'), table_name='api_call_logs')
    op.drop_table('api_call_logs')
    # ### end Alembic commands ###
